# Generated by Django 3.0.3 on 2020-04-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pic1', models.ImageField(upload_to='item_pics')),
                ('item_pic2', models.ImageField(upload_to='item_pics')),
                ('item_name', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('B', 'Book'), ('S', 'Stationary'), ('C', 'Coupon')], max_length=128)),
            ],
        ),
    ]
