# Generated by Django 3.0.3 on 2020-04-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminfo',
            name='item_pic1',
        ),
        migrations.RemoveField(
            model_name='iteminfo',
            name='item_pic2',
        ),
    ]
