# Generated by Django 3.0.3 on 2020-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200429_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='item_pic1',
            field=models.ImageField(null=True, upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='item_pic2',
            field=models.ImageField(null=True, upload_to='item_pics'),
        ),
    ]
