# Generated by Django 3.0.3 on 2020-04-30 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0003_auto_20200430_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='item_author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='item_des',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='item_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='item_type',
            field=models.CharField(choices=[('B', 'Book'), ('S', 'Stationary')], max_length=50, null=True),
        ),
    ]
