# Generated by Django 3.0.3 on 2020-04-30 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200430_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminfo',
            name='user',
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='post_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 19, 10, 850379), null=True),
        ),
    ]
