# Generated by Django 3.0.3 on 2020-04-30 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20200430_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='post_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 23, 17, 1, 283896), null=True),
        ),
    ]
