# Generated by Django 3.0.3 on 2020-05-01 04:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0013_auto_20200501_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='post_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 9, 45, 49, 733086), null=True),
        ),
        migrations.RemoveField(
            model_name='iteminfo',
            name='user',
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
