# Generated by Django 3.0.3 on 2020-04-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20200430_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
