# Generated by Django 3.0.3 on 2020-04-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_userprofileinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.ImageField(upload_to='media/profile_pics'),
        ),
    ]
