# Generated by Django 3.0.3 on 2020-04-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20200430_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
